version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiii_development
      MYSQL_USER: yutaro
      MYSQL_PASSWORD: yutaro
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: apiii.docker
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/yutaro/apiii
    environment:
      PORT: 9800
      DB_HOST: db
      DB_NAME: apiii_development
      DB_USER: yutaro
      DB_PASSWORD: yutaro
    ports:
      - '9800:9800'
    tty:
      true